### ISSUE TITLE
Why BSIPA include BeatsaberCustomUI in the refs

### ISSUE THREAD

**Issue by jiangdl** [nike4613/BeatSaber-IPA-Reloaded#21]
BSIPA is the basic tool for developing mod, why include BeatsaberCustomUI? In addition, where is musedasha_data in resfs.txt? According to the document git clone, I can't build it. Who can help me?

**Comment by nike4613** [comment]
BSIPA itself doesn't; that would be ModList which *is* specific to Beat Saber. It only builds in the Net4-x64 configuration, matching Beat Saber's.

As for that last point, what are you talking about? [`refs.txt` has had it since I added support for .NET 3](https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/blob/master/Refs/refs.txt#L32)

**Comment by jiangdl** [comment]
I get, Thanks very much~~~
