### ISSUE TITLE
System.TypeLoadException on launch: 'Could not resolve type from 0Harmony'

### ISSUE THREAD

**Issue by octatone** [nike4613/BeatSaber-IPA-Reloaded#38]
![image](https://user-images.githubusercontent.com/492289/77735720-54ed2400-700b-11ea-9141-bc7bd1a0333a.png)

**Comment by ben-struss** [comment]
Check your `Beat Saber\Beat Saber_Data\Managed` folder for an old version of `0Harmony.dll` (1.2.0.1) and if present, delete it. This might be a leftover from a old IPA version (around march/april 2019) when files were copied directly into this folder instead of `IPA\Libs`?

**Comment by nike4613** [comment]
@ben-struss is correct. Because of the load order during startup, it is not terribly feasible check and delete it during startup.

**Comment by octatone** [comment]
Thanks all, this worked for me

**Comment by Techwolf12** [comment]
I had this issue as well! It had a old library in the Managed folder. I just deleted the folder, re-verified game files and then patched again with ModAssistant and now it works! Thanks a bunch for this!

Since this issue was hard to find for me I will add some key words:
Could not load type of field 'IPA.Logging.StdoutInterceptor:harmony'
Could not resolve type with token 
0Harmony


May I also suggest to change the title to: "Harmony Could not resolve type with token due to old files"? :)
