### ISSUE TITLE
Mods not recognised when running Beat Saber under Wine (Linux)

### ISSUE THREAD

**Issue by ColonelPanic-42** [nike4613/BeatSaber-IPA-Reloaded#7]
I once had mods working when Beat Saber was on version 0.12.2. Then it updated and they stopped working.

I've tried to reinstall the mods onto the new version, but no matter what I try IPA doesn't even seem to get recognised. The `--verbose` argument does nothing when I add it to the game in Steam. The `--launch` argument run against IPA and the game exe directly doesn't work as the game seems to crash immediately on load. I've installed .NET 4.7.2 via winetricks/protontricks. I don't know how IPA is meant to hook into the game on load, as it doesn't look like it changes any files (only adding them), and I'm at a loss as to why it doesn't work. I've even copied the files over from a separate Windows machine that is working, and it still won't work for me.

What's worse, even rolling back to 0.12.2 in Steam doesn't work. I can't even get old versions of the mods to install and be recognised, the same problem happens with them now too. I can't understand what has changed, when it worked so perfectly before when I first installed it a couple months ago. If I could even get that working I would just stick to the old version.

I know Beat Saber is a Windows game and this isn't made with the idea of running under Wine/Linux being supported, but seeing as it USED to work I had hope of being at least pointed in the right direction or given some advice on how to debug this.

**Comment by Slaynash** [comment]
I just gave a check, and it seems that IPA.exe is unable to patch the game (or it isn't natively) and stops with an error:
![Capture d’écran de 2019-04-13 23-19-45](https://user-images.githubusercontent.com/5593503/56085400-d2dc0d80-5e42-11e9-9307-b25f3ef78824.png)

**Comment by ColonelPanic-42** [comment]
In my case it did "patch" as expected (although I ran it with Wine, against the same prefix Steam uses for the game, I presume in your attempt it may have tried to run with mono instead?). But no dice.

As mentioned in the original post as well, I even tried copying the entire game folder over from a working Windows install - while IPA injects as expected when run on that machine, it doesn't when run on mine. I also have a Windows VM that I use for the purpose of modding when modding tools refuse to run under Wine, so I clone the game files across to it, install the mods, then sync it back onto my Linux host. This worked the first time when I installed it months ago under 0.12.2, but now refuses to work whether I try for 0.12.2 or 0.13.2.

The only other change is when I did it months ago, I used the original mod tool from modsaber, which no longer works as everyone knows. But even so, I tried to get an older version of IPA and install manually, it still won't inject :(.

**Comment by nike4613** [comment]
For @Slaynash the problem is that it tries to use `GetKeyState` to check for uninstalls. (I should probably make that error catch properly) You should be able to manually copy everything out of `IPA/` and merge the `Data` folder with `Beat Saber_Data` and it should work fine.

@ColonelPanic-42 Does Wine use the same DLL resolution rules as Windows? The new injector works by placing a `winhttp.dll` proxy in the game main directory, so that it can be found and run first. It also does some hooking into calls to Mono from UnityEngine by looking up the module and replacing the jump address. You may also need to update Wine. If that doesn't work, let me know, and I'll send you a version that logs a bunch of info for me to try to help you.

That being said, I'm not sure if I want to spend the energy supporting Linux. If this is too wierd, there's a good likelihood of me just giving up. I am more than willing to integrate any fixes if you send a PR though.

**Comment by ColonelPanic-42** [comment]
@nike4613 I understand not wanting to spend the effort supporting Linux. You're writing a mod in your own time, unpaid, for a game designed to run on Windows, you're at least one step removed from where to push for support needs to be. At least you're happy to try :) and for that I'm grateful.

But this time you might have lucked out (as have I). Thank you for pointing me in the right direction. Apparently winhttp was the missing piece. I installed it via protontricks, and suddenly it's working! Either the builtin winhttp in Wine isn't good enough, or it needed the "Native, builtin" DLL override before it would pick it up.
